# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [67]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [68]:
weather_data = pd.read_csv("city_weather_date.csv")
weather_data.dropna()

,city,temp,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
0,bubaque,22.59,69,GW,1585037014,55,11.28,-15.83,22.59,7.11
1,klaksvik,4.00,100,FO,1585037014,86,62.23,-6.59,4.00,6.20
2,busselton,30.73,51,AU,1585037014,13,-33.65,115.33,31.11,3.35
3,dikson,-10.41,69,RU,1585037014,89,73.51,80.55,-10.41,2.60
4,lebu,14.39,100,CL,1585037014,98,-37.62,-73.65,14.39,2.11
...,...,...,...,...,...,...,...,...,...,...
560,victoria point,21.83,75,AU,1585037040,83,-27.58,153.30,23.00,1.50
561,kang,28.59,0,BW,1585037040,36,-23.68,22.79,28.59,3.81
562,carutapera,27.99,51,BR,1585037040,75,-1.20,-46.02,27.99,3.26
563,daru,24.69,100,PG,1585037040,93,-9.08,143.21,24.69,1.05
564,jeremie,19.39,41,HT,1585037040,84,18.65,-74.12,19.39,0.59

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [69]:
locations = weather_data[["Lat", "Lng"]]
humidity = weather_data["Humidity"].astype(float)

In [70]:
# Plot Heatmap
fig = gmaps.figure()

# Create heat layer
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, 
                                 dissipating=False, max_intensity=10,
                                 point_radius=1)

# Add layer
fig.add_layer(heat_layer)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
Narrow down the DataFrame to find your ideal weather condition. 

For example:
A max temperature lower than 80 degrees but higher than 70.
Wind speed less than 10 mph.
Zero cloudiness.
Drop any rows that don't contain all three conditions. You want to be sure the weather is ideal.
Note: Feel free to adjust to your specifications but be sure to limit the number of rows returned by your API requests to a reasonable number.
* Drop any rows will null values.

In [94]:
hotel_df = weather_data[(weather_data['Max Temp'] < 60) & 
                      (weather_data['Max Temp'] > 20) &
                      (weather_data['Cloudiness'] == 0) & 
                      (weather_data['Wind Speed'] < 10) ]
hotel_df

,city,temp,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
11,kirando,25.39,0,TZ,1585037015,69,-7.42,30.60,25.39,2.95
23,karasburg,32.09,0,NaN,1585037015,18,-28.02,18.75,32.09,3.04
33,karratha,30.29,0,AU,1585037016,72,-20.74,116.85,30.29,6.83
51,puerto ayora,22.78,0,EC,1585037016,86,-0.74,-90.35,22.78,0.45
58,la joya,22.22,0,MX,1585037017,55,18.67,-99.47,22.22,0.98
63,birao,36.29,0,CF,1585037017,7,10.28,22.79,36.29,7.68
102,moron,19.97,0,AR,1585037019,88,-34.65,-58.62,22.22,2.60
114,puerto escondido,20.79,0,MX,1585037019,78,15.85,-97.07,20.79,1.03
124,tautira,27.90,0,PF,1585037020,69,-17.73,-149.15,28.00,1.50
128,arraial do cabo,22.09,0,BR,1585037020,77,-22.97,-42.03,22.09,2.77
142,tecoanapa,21.99,0,MX,1585037021,73,16.52,-98.75,21.99,1.62
145,sur,24.19,0,OM,1585037021,46,22.57,59.53,24.19,4.51
221,marsh harbour,23.09,0,BS,1585037024,75,26.54,-77.06,23.09,3.71
223,lashio,30.29,0,MM,1585037025,15,22.93,97.75,30.29,2.89
249,port blair,27.99,0,IN,1585037026,69,11.67,92.75,27.99,6.14
261,west bay,25.00,0,KY,1585037026,82,19.37,-81.42,25.00,5.36
266,umm lajj,30.29,0,SA,1585037027,15,25.02,37.27,30.29,4.72
300,san patricio,23.49,0,MX,1585037028,76,19.22,-104.70,23.49,2.24
321,sao joao da barra,20.29,0,BR,1585037029,87,-21.64,-41.05,20.29,4.54
322,coahuayana,21.79,0,MX,1585037029,37,18.73,-103.68,21.79,0.98
419,matamoros,24.99,0,MX,1585037034,18,25.53,-103.25,24.99,4.58
436,khatra,35.49,0,IN,1585037034,17,22.98,86.85,35.49,4.22
442,pochutla,24.44,0,MX,1585037035,81,15.74,-96.47,24.44,4.79
457,jacmel,24.00,0,HT,1585037035,83,18.23,-72.53,24.00,3.10
461,asosa,37.09,0,ET,1585037036,8,10.07,34.53,37.09,2.10
463,richards bay,25.89,0,ZA,1585037036,73,-28.78,32.04,25.89,3.86
464,bloemfontein,22.00,0,ZA,1585037036,68,-29.12,26.21,22.00,2.10
474,hukuntsi,29.39,0,BW,1585036866,33,-24.00,21.75,29.39,4.63
480,vung tau,29.39,0,VN,1585037036,60,10.35,107.08,29.39,6.98
487,nizwa,22.29,0,OM,1585037037,16,22.93,57.53,22.29,2.83
500,chirilagua,26.89,0,SV,1585037037,65,13.22,-88.14,26.89,2.88
502,akyab,26.89,0,MM,1585037037,63,20.15,92.90,26.89,6.65
522,keti bandar,27.59,0,PK,1585037038,64,24.14,67.45,27.59,5.62
525,yamethin,35.29,0,MM,1585037039,14,20.43,96.15,35.29,6.66
526,ratnagiri,34.19,0,IN,1585037039,44,16.98,73.30,34.19,5.39
527,pandan,27.29,0,PH,1585037039,73,14.05,124.17,27.29,6.62
548,doha,24.09,0,QA,1585036968,36,25.29,51.53,25.00,3.10
561,kang,28.59,0,BW,1585037040,36,-23.68,22.79,28.59,3.81

In [95]:
hotel_df.reset_index(drop=True)

,city,temp,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
0,kirando,25.39,0,TZ,1585037015,69,-7.42,30.60,25.39,2.95
1,karasburg,32.09,0,NaN,1585037015,18,-28.02,18.75,32.09,3.04
2,karratha,30.29,0,AU,1585037016,72,-20.74,116.85,30.29,6.83
3,puerto ayora,22.78,0,EC,1585037016,86,-0.74,-90.35,22.78,0.45
4,la joya,22.22,0,MX,1585037017,55,18.67,-99.47,22.22,0.98
5,birao,36.29,0,CF,1585037017,7,10.28,22.79,36.29,7.68
6,moron,19.97,0,AR,1585037019,88,-34.65,-58.62,22.22,2.60
7,puerto escondido,20.79,0,MX,1585037019,78,15.85,-97.07,20.79,1.03
8,tautira,27.90,0,PF,1585037020,69,-17.73,-149.15,28.00,1.50
9,arraial do cabo,22.09,0,BR,1585037020,77,-22.97,-42.03,22.09,2.77
10,tecoanapa,21.99,0,MX,1585037021,73,16.52,-98.75,21.99,1.62
11,sur,24.19,0,OM,1585037021,46,22.57,59.53,24.19,4.51
12,marsh harbour,23.09,0,BS,1585037024,75,26.54,-77.06,23.09,3.71
13,lashio,30.29,0,MM,1585037025,15,22.93,97.75,30.29,2.89
14,port blair,27.99,0,IN,1585037026,69,11.67,92.75,27.99,6.14
15,west bay,25.00,0,KY,1585037026,82,19.37,-81.42,25.00,5.36
16,umm lajj,30.29,0,SA,1585037027,15,25.02,37.27,30.29,4.72
17,san patricio,23.49,0,MX,1585037028,76,19.22,-104.70,23.49,2.24
18,sao joao da barra,20.29,0,BR,1585037029,87,-21.64,-41.05,20.29,4.54
19,coahuayana,21.79,0,MX,1585037029,37,18.73,-103.68,21.79,0.98
20,matamoros,24.99,0,MX,1585037034,18,25.53,-103.25,24.99,4.58
21,khatra,35.49,0,IN,1585037034,17,22.98,86.85,35.49,4.22
22,pochutla,24.44,0,MX,1585037035,81,15.74,-96.47,24.44,4.79
23,jacmel,24.00,0,HT,1585037035,83,18.23,-72.53,24.00,3.10
24,asosa,37.09,0,ET,1585037036,8,10.07,34.53,37.09,2.10
25,richards bay,25.89,0,ZA,1585037036,73,-28.78,32.04,25.89,3.86
26,bloemfontein,22.00,0,ZA,1585037036,68,-29.12,26.21,22.00,2.10
27,hukuntsi,29.39,0,BW,1585036866,33,-24.00,21.75,29.39,4.63
28,vung tau,29.39,0,VN,1585037036,60,10.35,107.08,29.39,6.98
29,nizwa,22.29,0,OM,1585037037,16,22.93,57.53,22.29,2.83
30,chirilagua,26.89,0,SV,1585037037,65,13.22,-88.14,26.89,2.88
31,akyab,26.89,0,MM,1585037037,63,20.15,92.90,26.89,6.65
32,keti bandar,27.59,0,PK,1585037038,64,24.14,67.45,27.59,5.62
33,yamethin,35.29,0,MM,1585037039,14,20.43,96.15,35.29,6.66
34,ratnagiri,34.19,0,IN,1585037039,44,16.98,73.30,34.19,5.39
35,pandan,27.29,0,PH,1585037039,73,14.05,124.17,27.29,6.62
36,doha,24.09,0,QA,1585036968,36,25.29,51.53,25.00,3.10
37,kang,28.59,0,BW,1585037040,36,-23.68,22.79,28.59,3.81

In [96]:
hotel_data = []
hotel_not_exist = []

In [112]:
target_search = "hotel"
radius = 5000 

params = {
    "radius": radius,
    "keyword": target_search,
    "key": g_key
}

for index, row in hotel_df.iterrows():

    lat = row["Lat"]
    lng = row["Lng"]
    city = row["city"]
    country = row["Country"]

    # change location each iteration while leaving original params in place
    params["location"] = f"{lat},{lng}"

    # Use the search term: "International Airport" and our lat/lng
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # make request and print url
    name_address = requests.get(base_url, params=params)

    # convert to json
    name_address = name_address.json()

    # Since some data may be missing we incorporate a try-except to skip any that are missing a data point.
    try:
        hotel_data.append({"name":name_address["results"][0]["name"], 
                         "city": city,
                         "country": country})

    except:
        hotel_not_exist.append(index)
        print("Missing field/result... skipping.")

In [98]:
for row in hotel_not_exist:
    hotel_df.drop(row, inplace = True)

In [99]:
hotel_df.reset_index(drop=True,inplace = True)

In [100]:
city_hotel_df = pd.DataFrame(hotel_data)
narrowed_city_df = city_hotel_df.rename(columns={"name":"Hotel Name",
                                    "city":"City",
                                    "country":"Country"})
narrowed_city_df

,Hotel Name,City,Country
0,Lakeshore Lodge,kirando,TZ
1,Sunset Chalets,karasburg,NaN
2,ibis Styles Karratha,karratha,AU
3,Albatross,puerto ayora,EC
4,Hotel Cabildo,moron,AR
5,Selina Puerto Escondido,puerto escondido,MX
6,Hotel da Canoa,arraial do cabo,BR
7,Hotel Garapacho,tecoanapa,MX
8,Sur Plaza Hotel,sur,OM
9,Abaco Beach Resort,marsh harbour,BS
10,Mansu Hotel,lashio,MM
11,Sinclairs Bayview Port Blair,port blair,IN
12,The Westin Grand Cayman Seven Mile Beach Resor...,west bay,KY
13,عروس الشاطئ للوحدات السكنية المفروشة,umm lajj,SA
14,Grand Isla Navidad Resort,san patricio,MX
15,Pousada Kactus,sao joao da barra,BR
16,Hotel Posada Navideña,coahuayana,MX
17,Oishi Plaza,khatra,IN
18,Hotel Alebrijes,pochutla,MX
19,Manoir Adriana Hotel,jacmel,HT
20,Bamboo Paradise Hotel,asosa,ET
21,BON Hotel Waterfront Richards Bay,richards bay,ZA
22,Protea Hotel by Marriott Bloemfontein,bloemfontein,ZA
23,Entabeni Hotel,hukuntsi,BW
24,OYO 331 Jupiter Hotel,vung tau,VN
25,Antique Inn - Nizwa,nizwa,OM
26,"Hotel Miraflores, Playa Las Flores, El Salvador",chirilagua,SV
27,Noble Hotel,akyab,MM
28,yay tu ma hotel,yamethin,MM
29,Hotel Sea Fans,ratnagiri,IN
30,Bonifacio Lodge,pandan,PH
31,"Mandarin Oriental, Doha",doha,QA
32,Kang Ultra Stop,kang,BW

In [113]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
# **row take key="value" from each row
hotel_info = [info_box_template.format(**row) for index, row in narrowed_city_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [111]:
fig = gmaps.figure()

heat_layer = gmaps.heatmap_layer(locations, 
                                 dissipating=False, 
                                 max_intensity=100)


marker_layer = gmaps.marker_layer(locations, info_box_content = hotel_info)


# Add marker layer ontop of heat map
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Display Map
fig

Figure(layout=FigureLayout(height='420px'))